### ISSUE TITLE
可以和plc 通讯嘛

### ISSUE THREAD

**Issue by Andjdd** [ElectApp/ModbusTCP#1]
可以和plc 通讯嘛

**Comment by ElectApp** [comment]
This is android app. It connect a Modbus slave via Wi-Fi. If your PLC has Wi-Fi connection, so this app can work.
You can test at here -> [https://play.google.com/store/apps/details?id=com.tohighway.modbusv4](url) It may malfunction on some mobiles. because I haven't updated for a long time.
